# Generated by Django 3.2.5 on 2021-08-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followsList',
        ),
        migrations.AddField(
            model_name='user',
            name='followsList',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
