# Generated by Django 3.2.5 on 2021-08-16 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210817_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followsList',
        ),
        migrations.AddField(
            model_name='user',
            name='followsList',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
