# Generated by Django 3.2.5 on 2021-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210817_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followersCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='followsCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
