# Generated by Django 3.2.5 on 2021-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210817_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LikedList',
            field=models.ManyToManyField(blank=True, related_name='userLikes', to='network.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='userPost', to='network.Post'),
        ),
    ]
